### ISSUE TITLE
Marking packages with pacman -D

### ISSUE THREAD

**Issue by itsdeadguy** [excalibur1234/pacui#3]
Does PacUI have the ability to mark packages as dependencies or explicitly installed? If not, would it be possible to add this?

**Comment by excalibur1234** [comment]
it is easy to mark a package as explicitly installed: "(force) remove package" from your system and install it again. this will mark a package as explicitly installed and therefore never mark it as "orphaned".

i do not see any reason to mark a package as dependency: if you do that, the "clean system" option will see that package as orphaned and offers to remove it for you. you can simply "force remove package" to do effectively the same.
if you disagree with my point of view, please describe a non-abstruse use case in which this is actually useful or beneficial.

i try to keep the options in pacui at a minimum. every option should either :
- offer a really useful feature, which most people do not know about, or
- be useful when your system is broken and you only have a tty to work with (as has happened to me multiple times), or
- combine multiple things and therefore increase convenience for the user.


edit: feel free to reopen this issue, if you want to discuss it further.
