### ISSUE TITLE
Without yay, cleaning orphans exits the entire app with 1

### ISSUE THREAD

**Issue by freed00m** [excalibur1234/pacui#31]
Hi, 
When I use 2 Maintain option 
the pacui exits during 

yaourt -Qdt exits with 1 and the entire pacui exits with 1 also.

I discovered yay so I am not mad but should be fixed for those who are not using yay.

**Comment by excalibur1234** [comment]
you are right.
thanks for the report!

"yaourt -Qdt" exits with error code 1 when orphans are not removed.
i have just [fixed this bug](https://github.com/excalibur1234/pacui/commit/d6fdb3ab73b983bdf75d107dd41e4725a364deb5), which caused pacui to quit, too.

please reopen this issue, when you think it is necessary.
