### ISSUE TITLE
defaul editor of pacui

### ISSUE THREAD

**Issue by jemadux** [excalibur1234/pacui#36]
i am vim guy , how can change the defaul editor of pacUi ?

**Comment by excalibur1234** [comment]
pacui's "edit config files" option has used by default the $EDITOR environment variable for a long time. if this was not set, it used nano instead.

but i have just checked the code again and found that "visudo" (which is used to edit the "sudoers" file) always uses nano as editor.
i have changed it to use $SUDO_EDITOR by default (but if this is not set, nano gets used). visudo uses $SUDO_EDITOR by default.
the help page explains this as well, now.

please install pacui-git and set the environment variables mentioned above to your liking. 
my preliminary testing of $SUDO_EDITOR variable was not successful, but the code should work as i explained it above. i have not properly set my environment variables, though.
please report back, whether it works for you or not.

**Comment by excalibur1234** [comment]
have you done any testing?
does pacui work with vim when you set $EDITOR and $SUDO_EDITOR environment variables?

p.s.: you can set your environment variables in multiple ways:

- edit your `/etc/environment` file (e.g. with "`pacui c`") and add the following lines. this will not work, if you have set these environment variables in other places:
   ```
   EDITOR=/usr/bin/vim
   SUDO_EDITOR=/usr/bin/vim
   ```
- add the following lines to the bottom of your `~/.bashrc` file:
   ```
   export EDITOR="/usr/bin/vim" 
   export SUDO_EDITOR="/usr/bin/vim" 
   ```
- more ways of editing your environment variables are described here: https://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables

**Comment by excalibur1234** [comment]
i have done tests with these environment variables and everything works as expected.

i consider this issue solved. if this is not the case, please reopen it.
