### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by phineaslorcan** [excalibur1234/pacui#47]
I know, I stuck this in the issue category. I just wanted to take a moment to properly thank you for all your hard work, and this was the only place I could see to do so. So with that, thank you! 

I currently develop  another Arch-based distro called Reborn OS, and as of late a a few users were mentioning in distress how your package got pulled from the AUR. So I looked it up, and in response have added your package to the official Reborn-OS Repository! I know that being a smaller distro, this will not lend you help in any great form, but I thought you might appreciate just knowing that there are others even outside of Manjaro who value your dedication, product, and work - holding you in high esteem. I doubt we can change Arch, but at least we can help your project live on. 

On a happier note, I'll be contacting the Antergos devs soon regarding the possibility of them adding pacui to their repo as well - if that is fine with you. Perhaps they can reach a larger audience! 

And once again, thank you so much for all you have done. You truly have - and continue to - add to the Arch community. And by that, I am including all Arch derivatives, not just Arch itself.

**Comment by excalibur1234** [comment]
thanks for your kind words.
it is motivating to see others valuing your contribution.

feel free to discuss / report problems / send pull requests here or in the manjaro forum thread: https://forum.manjaro.org/t/pacui-bash-script-providing-advanced-pacman-and-yay-pikaur-aurman-pakku-trizen-pacaur-functionality-in-a-simple-ui/677. i read the manjaro forum regularly and more often, though. 

as i have mentioned in a [manjaro forum post](https://forum.manjaro.org/t/pacui-removed-from-aur/54716/26?u=excalibur1234), you can either use the PKGBUILD / PKGBUILD_AUR or PKGBUILD-git files (at least for inspiration how) to build pacui for rebornOS. should you want/need a different PKGBUILD, you can send it to me or make a pull request and i add it here. then, i can keep it up to date, e.g. if a dependency or other stuff changes and you have less work to do.

if you are OK with it, i can also ping you here (or as @keegan in the manjaro forum - what do you prefer?) when i release a new pacui stable version.

**Comment by phineaslorcan** [comment]
> as i have mentioned in a manjaro forum post, you can either use the PKGBUILD / PKGBUILD_AUR or PKGBUILD-git files (at least for inspiration how) to build pacui for rebornOS. should you want/need a different PKGBUILD, you can send it to me or make a pull request and i add it here. then, i can keep it up to date, e.g. if a dependency or other stuff changes and you have less work to do.

Thank you so much! I've already snagged a copy of your regular PKGBUILD ;) . So far, it's working perfectly! My next plan is to integrate it directly into our "Optional Advanced Programs" category in our installer.

> if you are OK with it, i can also ping you here (or as @keegan in the manjaro forum - what do you prefer?) when i release a new pacui stable version.

Whichever works best for you works for me! I'm not a huge Github user after the whole M$ thing, but I do come on occasionally (hence why it's taken me so long to see and reply to your message. For that, I am truly sorry. Life got busy for me and I haven't had the time to keep up with everything I would have liked to.) I just created a Manjaro user account a month or so ago, and think my username there is @keeganmilsten - same as it is here :) . Hopefully that makes it easier to remember!

**Comment by excalibur1234** [comment]
@keeganmilsten version 1.13 of pacui has been released. i have pinged you on the manjaro forum, too.

**Comment by comShadowHarvy** [comment]
i know i am late getting to this, and i am not really a developer, i found out you where pulled from AUR after i found this, and because most of my systems at home use reborn i was unaware. but i want to thank you so much for what you have done here, it has made most of my work maintaining them so much easier. 

Just wanted to thank you for your part in making ARCH easier and more approachable for the less tech savvy.
