### ISSUE TITLE
ion is incompatible

### ISSUE THREAD

**Issue by unmellow** [excalibur1234/pacui#48]
![bug](https://user-images.githubusercontent.com/30985587/47448695-ab0ec580-d78e-11e8-8802-48943a90c61c.png)

this happens whenever I use [ion-shell](https://gitlab.redox-os.org/redox-os/ion)
to be clear whether ion is my login shell or I just switched to it this still happens

**Comment by excalibur1234** [comment]
you are probably using pacui 1.11.
pacui-git adds an extra line, which forces itself (and fzf, with which your are having problems) to use bash:
https://github.com/excalibur1234/pacui/blob/0ec41dc73fee75508bceacaec8b8491b64439e4e/pacui#L2

pacui-git works fine for me with ion shell. please try the latest git version of pacui and report back, whether this is the case for you as well.
if you cannot test the git version, just wait for pacui 1.12 before reporting back. i might release it in a week or two...

**Comment by unmellow** [comment]
thanks, I don't normally get the git version of stuff because it takes so long to compile but this is a shell script so that's not a problem lol

edit: forgot to close
