### ISSUE TITLE
p3wm support

### ISSUE THREAD

**Issue by mberlinger3** [excalibur1234/pacui#62]
Adding p3wm support might be beneficial to allow for 3-way pacnew merging. I wrote a script in the following link for detecting pacnew files and opening them with p3wm. 

https://github.com/5long/p3wm/issues/9

**Comment by excalibur1234** [comment]
Please read [this chapter](https://github.com/excalibur1234/pacui#diff-program) in the documentation, which i have just added.

I am closing this topic. Should you have further questions, please reopen it again.
