### ISSUE TITLE
pacman -S pacui on Manjaro ARM => no target found pacui

### ISSUE THREAD

**Issue by freed00m** [excalibur1234/pacui#63]
I see there is arch=(any) why I cannot install it on Manjaro ARM ? 

There is core community and extra in my mirrorlist

EDIT: I am usin pinephone 3gbram edition

**Comment by excalibur1234** [comment]
Sorry, i do not own any ARM device and therefore cannot test this.
I assume that "pacui" was not build and put in the ARM repository.

It should be possible to [manually install](https://github.com/excalibur1234/pacui#manual-installation) PacUI instead.

I am closing this topic.
Please reopen it, if you have further questions.
