### ISSUE TITLE
Remove sudo as dependency

### ISSUE THREAD

**Issue by dnorhoj** [excalibur1234/pacui#65]
I would really like to see support for doas, as I can't install pacui without having sudo installed.

**Comment by excalibur1234** [comment]
As described [here](https://github.com/excalibur1234/pacui#dependencies), sudo is a hard dependency of PacUI.
It would not be a lot of work to add "doas", but it would make the code much more illegible. I want to avoid this.

If you want to use PacUI, i recommend to install it [manually](https://github.com/excalibur1234/pacui#manual-installation). After step 1, you can open the "pacui" file and search and replace "sudo" with "doas". Then, continue with step 2.

I am closing this ticket. 
Should you have further questions, please reopen it again.
